Removing bundles/

---> Making bundle: binary (in bundles/binary)
Building static bundles/binary-daemon/dockerd (linux/amd64)...
+ tee /home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt/build_dir/target-x86_64_musl/dockerd-27.3.1/go.mod
module github.com/docker/docker

go 1.21
+ trap 'rm -f "${ROOTDIR}/go.mod"' EXIT
+ GO111MODULE=on
+ GOTOOLCHAIN=local
+ go build -mod=vendor -modfile=vendor.mod -o bundles/binary-daemon/dockerd -tags 'netgo osusergo static_build ' -ldflags '-w -X "github.com/docker/docker/dockerversion.Version=27.3.1" -X "github.com/docker/docker/dockerversion.GitCommit=41ca978" -X "github.com/docker/docker/dockerversion.BuildTime=2026-08-12T03:53:45.000000000+00:00" -X "github.com/docker/docker/dockerversion.PlatformName=" -X "github.com/docker/docker/dockerversion.ProductName=" -X "github.com/docker/docker/dockerversion.DefaultProductLicense="  -extldflags -static ' -gcflags= github.com/docker/docker/cmd/dockerd
+ rm -f /home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt/build_dir/target-x86_64_musl/dockerd-27.3.1/go.mod
Created binary: bundles/binary-daemon/dockerd
Copying nested executables into bundles/binary-daemon
cp: cannot stat '': No such file or directory
make[3]: *** [Makefile:185: /home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt/build_dir/target-x86_64_musl/dockerd-27.3.1/.built] Error 1
make[3]: Leaving directory '/home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt/feeds/packages/utils/dockerd'
time: package/feeds/packages/dockerd/compile#2.21#1.01#11.70
    ERROR: package/feeds/packages/dockerd failed to build.
make[2]: *** [package/Makefile:176: package/feeds/packages/dockerd/compile] Error 1
make[2]: Leaving directory '/home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt'
make[1]: *** [package/Makefile:170: /home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt'
make: *** [/home/runner/work/openwrt_immortalwrt/openwrt_immortalwrt/openwrt/include/toplevel.mk:233: world] Error 2
Error: Process completed with exit code 2.
